//your boilerplate config come here
module.exports = {
    APPLICATION_NAME: 'EQUITY_MASTER_SERVICE',
    CONSOLE_LOG : true,
    REQUEST_RESPONSE_LOGGER : 'EQUITY_MASTER_RESQUEST_RESPONSE_LOGGER',
    SERVICE_CALL_LOGGER : 'EQUITY_MASTER_SERVICE_CALL_LOGGER',
    HEADER_RESPONSE_KEY : 'x-hissitaito-id'
};